	SUBROUTINE ATI.VIN.CHECKACCOUNTEXIST
	
	$INSERT I_COMMON
    $INSERT I_EQUATE
	$INSERT I_F.ATI.TH.EC.USERNAME
	$INSERT I_F.ACCOUNT
	
	Y.ACCOUNT = R.NEW(EC.USER.SAVING.AC)
	
	FN.ACCOUNT = 'F.ACCOUNT'
	F.ACCOUNT = ''
	CALL OPF(FN.ACCOUNT,F.ACCOUNT)
	CALL ATI.VIN.READACCOUNT(FN.ACCOUNT, Y.ACCOUNT, R.ACCOUNT, F.ACCOUNT, ERR.ACCOUNT)
	IF (R.ACCOUNT EQ '') THEN
		AF = EC.USER.SAVING.AC
		ETEXT = 'Ga ada nih'
		CALL STORE.END.ERROR
	END
	RETURN
END